### ISSUE TITLE
ONNX

### ISSUE THREAD

**Issue by wanglong001** [tracel-ai/burn#1130]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by antimora** [comment]
I will look into this soon. I have been busy with PyTorch import implementation.

**Comment by polarathene** [comment]
## Reproduction

For reference, using the current git version of Burn (_has some improvements since the latest release tag [`v0.17.1`](https://github.com/tracel-ai/burn/releases/tag/v0.17.1)_).

Reproduction uses [this `compose.yaml`](https://github.com/tracel-ai/burn/issues/1714#issuecomment-2952373124).

No specific ONNX model linked, assuming YOLOv5 (v7.0 release): https://github.com/ultralytics/yolov5/releases/tag/v7.0

```bash
ONNX_MODEL_URL='https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5n.onnx' \
docker compose run --rm -it burn-onnx-import cargo build
```

```rust
   INFO onnx_ir::from_onnx: Parsing ONNX file: src/model/example.onnx
  DEBUG onnx_ir::from_onnx: Number of nodes: 263
  DEBUG onnx_ir::from_onnx: Number of inputs: 1
  DEBUG onnx_ir::from_onnx: Number of initializers: 120
  DEBUG onnx_ir::from_onnx: Number of outputs: 1
  DEBUG onnx_ir::from_onnx: Opset domain: "<default>", version: 17
  ERROR burn_import::logger: PANIC => panicked at /root/.cargo/git/checkouts/burn-6c277d792b0d5d7a/1f5ccd4/crates/onnx-ir/src/ir.rs:38:33:
  invalid tensor model.0.conv.weight
```

**Comment by antimora** [comment]
I checked, it's failing on a brand new issue:

```
DEBUG onnx_ir::from_onnx: Adding node "reshape6"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Concat"
DEBUG onnx_ir::from_onnx: Renaming node "/model.24/Concat_3" to "concat17"
DEBUG onnx_ir::rank_inference: Inferring rank for node: concat17
DEBUG onnx_ir::node::concat: Concat rank inference for node concat17
DEBUG onnx_ir::node::concat: Concat using tensor input rank for concat17: 3
DEBUG onnx_ir::node::concat: Concat output rank for concat17: 3
DEBUG onnx_ir::rank_inference: Rank inference result for concat17: [Argument { name: "output0", ty: Tensor(TensorType { elem_type: Float16, rank: 3, static_shape: None }), value: None, passed: false }]
DEBUG onnx_ir::from_onnx: Adding node "concat17"
 INFO onnx_ir::from_onnx: Finished parsing ONNX file: ./out/yolov5n.onnx
DEBUG burn_import::onnx::to_burn: Writing debug onnx graph file: "./out/yolov5n.onnx.txt"
DEBUG burn_import::onnx::to_burn: Writing debug graph file: "./out/yolov5n.graph.txt"
DEBUG burn_import::burn::graph: Registering node => 'conv2d'
ERROR burn_import::logger: PANIC => panicked at crates/burn-import/src/onnx/to_burn.rs:1880:18:
Unsupported tensor type Float16

thread 'main' panicked at crates/burn-import/src/onnx/to_burn.rs:1880:18:
Unsupported tensor type Float16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
(onnx-tests) [burn-import]%
```

This probably will be fixed by: https://github.com/tracel-ai/burn/pull/3574

Closing the original issue.
