### ISSUE TITLE
Strange gpu resources usage with candle(cuda) backend on wsl2

### ISSUE THREAD

**Issue by yiyueawa** [tracel-ai/burn#1556]
**Describe the bug**
while im trying to move my burn project to linux, bacause wsl's bad vaulkan support, i use candle backend instead  of wgpu backend

then, strange and unexprcted behavior happend: my program crashed, because of `OOM`(may be?)

a part of log
``` log

2024-03-29T14:31:18.781360Z  INFO burn_train::learner::train_val: Fitting Model[num_params=12730]    
2024-03-29T14:31:18.784569Z  INFO burn_train::learner::epoch: Executing training step for epoch 1    
2024-03-29T14:31:22.254104Z ERROR burn_train::learner::log: PANIC => panicked at /home/yiyue/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/burn-candle-0.12.1/src/backend.rs:47:83:
called `Result::unwrap()` on an `Err` value: Cuda(Cublas(CublasError(CUBLAS_STATUS_ALLOC_FAILED)))    
2024-03-29T14:31:22.260134Z ERROR burn_train::learner::log: PANIC => panicked at /home/yiyue/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/burn-candle-0.12.1/src/backend.rs:47:83:
called `Result::unwrap()` on an `Err` value: Cuda(Cublas(CublasError(CUBLAS_STATUS_ALLOC_FAILED)))    
2024-03-29T14:31:22.273330Z ERROR burn_train::learner::log: PANIC => panicked at /home/yiyue/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/burn-candle-0.12.1/src/backend.rs:47:83:
...

2024-03-29T15:11:03.627465Z  INFO burn_train::learner::epoch: Iteration 15    
2024-03-29T15:11:03.690694Z ERROR burn_train::learner::log: PANIC => panicked at /home/yiyue/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/burn-core-0.12.1/src/data/dataloader/multithread.rs:129:29:
called `Result::unwrap()` on an `Err` value: RecvError


```

then a rerun the program and open taskmanager, i found that the program uses many gpu resources, the memory usage can up to 7.6G and then down to 2G ... you can easily know this by the screenshot down

![sb](https://github.com/tracel-ai/burn/assets/97959381/ed634b8b-829c-4176-8054-540f1cecda6e)

i change the batch_size from 500 to 100, then the program is able to run but very slow, 30x time usage and 3x gpu usage than the same program with wgpu backend

maybe this has to do with strange enviroment: archlinux (wsl2)?

```
yiyue@terc ~> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:19:38_PST_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0

yiyue@terc ~> rustc --version
rustc 1.79.0-nightly (0824b300e 2024-03-24)

yiyue@terc ~> uname -a
Linux terc 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 GNU/Linux
```

here are the [code](https://github.com/twhice/learn-deep-learning)

**Comment by antimora** [comment]
Outdated and not planned.
