### ISSUE TITLE
Support ONNX subgraph for silero vad model

### ISSUE THREAD

**Issue by smallbraineng** [tracel-ai/burn#1941]
### Feature description

I'd love support for the `ConstantOfShape` (9) ONNX Operator, which isn't currently implemented according to the docs

### Feature motivation

To use [Silero VAD](https://github.com/snakers4/silero-vad) on embedded hardware / really cheaply in wasm

The operators needed for that are
```
ai.onnx;1;Not
ai.onnx;9;ConstantOfShape
ai.onnx;11;Conv
ai.onnx;13;Cast,Concat,Equal,Gather,Pad,ReduceMean,Size,Split,Sqrt,Squeeze,Unsqueeze
ai.onnx;14;Add,LSTM,Relu
ai.onnx;15;Pow,Shape
ai.onnx;16;Identity,If
com.microsoft;1;FusedConv
```

<3

**Comment by antimora** [comment]
there is an outstanding pr for constant https://github.com/tracel-ai/burn/issues/1815

**Comment by antimora** [comment]
The direct link file: https://github.com/snakers4/silero-vad/blob/master/files/silero_vad.onnx

Attached: 
[silero_vad.onnx.zip](https://github.com/user-attachments/files/16045486/silero_vad.onnx.zip)


In addition to missing ConstantOfShape, Burn ONNX needs to support subgraphs, see #724.

CCing @skewballfox. This is something to consider for our future design.

**Comment by smallbraingames** [comment]
Ah got it, that makes sense. Looks like that will take some larger design changes?

**Comment by antimora** [comment]
Yes, that's correct. But it is good that you file now we know to prioritize this feature. I have been wanting to use it as well.

**Comment by smallbraingames** [comment]
Love it. Can't wait to use it and have a 10x smaller wasm

**Comment by polarathene** [comment]
Status update almost a year later. The ONNX file location has [since changed](https://github.com/snakers4/silero-vad/commit/f0d880d79c50d36c9c014e282a89fe42b0683120) (July 2024), with only the latest v5 ONNX model [offered here](https://github.com/snakers4/silero-vad/tree/master/src/silero_vad/data) (_[replacing v4 at the end of June 2024](https://github.com/snakers4/silero-vad/commit/fd1f1a62b75ec5824993aa4062b55c0965b9621b)_).

So for reference here are the permalinks:

- [v4](https://github.com/snakers4/silero-vad/blob/v4.0/files/silero_vad.onnx) (Oct 2022)
- [v5](https://github.com/snakers4/silero-vad/blob/v5.1.2/src/silero_vad/data/silero_vad.onnx) (July 2024)

---

## Reproduction

Using [this `compose.yaml`](https://github.com/tracel-ai/burn/issues/1714#issuecomment-2952373124).

### v4

```bash
ONNX_MODEL_URL=https://github.com/snakers4/silero-vad/raw/v4.0/files/silero_vad.onnx docker compose run --rm -it burn-onnx-import cargo build
```

```rust
   INFO onnx_ir::from_onnx: Parsing ONNX file: src/model/example.onnx
  ERROR burn_import::logger: PANIC => panicked at /root/.cargo/git/checkouts/burn-6c277d792b0d5d7a/1f5ccd4/crates/onnx-ir/src/util.rs:60:9:
  Only the standard ONNX domain is supported
```

Similar to Depth Anything V2, Burn presently only supports implementing the standard ONNX domain, preventing this model to be supported. AFAIK there is no tracking issue/roadmap for supporting additional domains at this time.

**EDIT:** [This issue comment](https://github.com/tracel-ai/burn/issues/724#issue-1872097914) references v4 as using subgraphs, but presumably the error above is another blocker as it doesn't match the v5 failure regarding subgraph support.

### v5

```bash
ONNX_MODEL_URL=https://github.com/snakers4/silero-vad/raw/v5.1.2/src/silero_vad/data/silero_vad.onnx docker compose run --rm -it burn-onnx-import cargo build
```

```rust
  DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "If"
  ERROR burn_import::logger: PANIC => panicked at /root/.cargo/git/checkouts/burn-6c277d792b0d5d7a/1f5ccd4/crates/onnx-ir/src/proto_conversion.rs:143:73:
  called `Result::unwrap()` on an `Err` value: VariantNotFound
```

This one I believe is referring to Subgraph support, tracking issue: https://github.com/tracel-ai/burn/issues/724 (_**EDIT:** Yes, a comment the in July 2024 [reports the same failure](https://github.com/tracel-ai/burn/issues/724#issuecomment-2241068553)_)

**Comment by antimora** [comment]
ConstantOfShape is now supported but Silero has subgraphs and `if` OP. This is will be supported by https://github.com/tracel-ai/burn/issues/724

**Comment by antimora** [comment]
Added Silero VAD ONNX model verification and it's blocked on.

1. Pad op not supporting `reflect` mode.
2. Also LSTM missing

Subgraph is fixed via #3936

**Comment by antimora** [comment]
As much as I could this make work, there is a fundamental issue in silero-vad that burn-import cannot produce rust code. Specifically, silero-vad contains if-subgraph nodes that output different rank tensors. Burn currently details with static ranks and dynamic rank tensors are not supported (see https://github.com/tracel-ai/burn/issues/3624). CCing @nathanielsimard 

I requested silero-vad team to improve ONNX graph outputs here: https://github.com/snakers4/silero-vad/issues/728

**Comment by antimora** [comment]
Yay, silero-vad came back and provided if node free version: https://github.com/snakers4/silero-vad/issues/728#issuecomment-3617051922

https://github.com/snakers4/silero-vad/blob/master/src/silero_vad/data/silero_vad_op18_ifless.onnx

I haven't tried it yet but I'll check it out
