### ISSUE TITLE
Error importing the FaceONNX model `landmarks_68_pfld`: `Only tensor input is valid but received: Shape(4)`

### ISSUE THREAD

**Issue by SimonBrandner** [tracel-ai/burn#2115]
```
ERROR burn_import::logger: PANIC => panicked at /home/simon/.cargo/git/checkouts/burn-178c6829f420dae1/f7639bd/crates/onnx-ir/src/dim_inference.rs:814:15:
Only tensor input is valid but received: Shape(4)
```

Link to model: https://drive.google.com/file/d/1qgM6ZqMyB60FYlzzxNDyUefifLS0lhag/view?usp=sharing

**Comment by mepatrick73** [comment]
PR #2120 should fix the mentionned issue

**Comment by antimora** [comment]
> [c2b6318](https://github.com/tracel-ai/burn/commit/c2b6318fc3232536c91910923e09ad0f9f30763a) switched to using `ArgType::Shape` for the output of the shapes-Operator instead of just using a 1D `Tensor`.
> 
> As far as I can tell, the ONNX Spec does not differentiate between Shapes and other 1D Tensors; each time an input or output argument contains a shape, the spec defines it as
> 
> > 1D tensor. The shape of the expected output tensor.
> 
> or similar.
> 
> Now, I can see 2 ways forward:
> 
> * Differentiating Args that are a shape vs. just a random 1D Tensor might still be useful, but then other functions like gather need to also work on Shapes.
> * Or the Shape ArgType is dropped in favor of just using 1D Tensors everywhere they were used, aligning with how the ONNX spec does it.
> 
> Is there a way to know if many operators besides `Gather` are usually fed the output from the `Shape` Op?

We started using Shape arg/input/output type. Please see my comment here in the PR: https://github.com/tracel-ai/burn/pull/1815#issuecomment-2212032793

Although ONNX spec does not differentiate types (scalar, shape, tensor are all the same), Burn and other frameworks do. Shape calculation will be a overkill if we use tensor ops because shape information is stored on CPU so it will require constant syncing from GPU device. 

Our reshape onnx node can accept Shape arg type.

**Comment by SimonBrandner** [comment]
After https://github.com/tracel-ai/burn/pull/2128 was merge this is now:

```
ERROR burn_import::logger: PANIC => panicked at /home/simon/.cargo/git/checkouts/burn-178c6829f420dae1/27ca6ce/crates/onnx-ir/src/dim_inference.rs:819:9:
Gather: indices tensor rank above 1 not supported    
```

**Comment by laggui** [comment]
Yeah the gather op translates to `tensor.select(dim, indices)` but the indices are expected to be 1d. There's a discrepancy between ONNX spec and the Burn tensor method.

**Comment by SimonBrandner** [comment]
After https://github.com/tracel-ai/burn/commit/be5eb910d4e8f91a7162c523a2d390d01a41a12d:

```
ERROR burn_import::logger: PANIC => panicked at /home/simon/.cargo/git/checkouts/burn-178c6829f420dae1/be5eb91/crates/burn-import/src/onnx/to_burn.rs:1245:18:
Can't transform scalar to tensor.    
```

**Comment by SimonBrandner** [comment]
This has evolved to:

```
ERROR burn_import::logger: PANIC => panicked at /home/simon/.cargo/git/checkouts/burn-178c6829f420dae1/c94e743/crates/burn-import/src/onnx/op_configuration.rs:1056:9:
Reshape: shape tensor must be present for Node { node_type: Reshape, name: "reshape1", inputs: [Argument { name: "conv2d62_out1", ty: Tensor(TensorType { elem_type: Float32, dim: 4, shape: Some([1, 3, 640
, 640]) }), value: None, passed: false }, Argument { name: "concat15_out1", ty: Tensor(TensorType { elem_type: Float32, dim: 1, shape: None }), value: None, passed: false }], outputs: [Argument { name: "res
hape1_out1", ty: Tensor(TensorType { elem_type: Float32, dim: 0, shape: None }), value: None, passed: false }], attrs: {} }    
```

**Comment by antimora** [comment]
Tested the model. it seems to be fixed by https://github.com/tracel-ai/burn/pull/3381
