### ISSUE TITLE
ONNX import issue: `ceil_mode is not supported` in `avg_pool1d_config()`

### ISSUE THREAD

**Issue by SimonBrandner** [tracel-ai/burn#2132]
```
ERROR burn_import::logger: PANIC => panicked at /home/simon/.cargo/git/checkouts/burn-178c6829f420dae1/d770b1f/crates/burn-import/src/onnx/op_configuration.rs:374:9:
ceil_mode is not supported
```

Link to model: [drive.google.com/file/d/1E6fNKzGE3_JhEokgqqHDqJxwqw3UUku9/view?usp=drive_link](https://drive.google.com/file/d/1E6fNKzGE3_JhEokgqqHDqJxwqw3UUku9/view?usp=drive_link)

**Comment by antimora** [comment]
This requires enhancement to Burn's average pool implementation.

**Comment by mepatrick73** [comment]
This probably requires rewriting the pooling tensor operations in CubeCL. They are currently written in "pseudo-assembly" and I don't see a good reason to try and maintain that version.

**Comment by mepatrick73** [comment]
I'm locking this behind #2140

**Comment by raphaelmenges** [comment]
I get a similar error but for `avg_pool2d`:

> `thread 'main' (34885003) panicked at /Users/raphael/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/onnx-ir-0.19.0/src/node/avg_pool2d.rs:60:9: ceil_mode is not supported`

I guess it is the same "problem" 😬

**Comment by laggui** [comment]
@raphaelmenges yepp, we do not support ceil mode for pooling in burn right now.. so any ONNX models that use this configuration will panic 🥲 

https://github.com/tracel-ai/burn/blob/89de0e13926291028817983d65c242906d3b649b/crates/burn-nn/src/modules/pool/avg_pool2d.rs#L33-L55

**Comment by torsteingrindvik** [comment]
Same for LPIPS specifically for the squeeze variant, the others are ok:

```python
import lpips
import torch

def main(size=(1920, 1080)):
    (width, height) = size

    for net in ["alex", "vgg", "squeeze"]:
        print(f"Exporting {net}")

        loss_fn = lpips.LPIPS(net=net)
        loss_fn.eval()

        dummy_input_img0 = torch.randn(1, 3, height, width)
        dummy_input_img1 = torch.randn(1, 3, height, width)

        torch.onnx.export(
            loss_fn,
            (dummy_input_img0, dummy_input_img1),  # Model inputs as a tuple
            f"../../onnx/lpips_{net}.onnx",  # Output ONNX file name
            export_params=True,  # Export trained parameters
            opset_version=21,  # ONNX opset version (choose a compatible version)
            do_constant_folding=True,  # Apply constant folding optimization
            input_names=["input0", "input1"],  # Input names for the ONNX graph
            output_names=["output"],  # Output name for the ONNX graph
            dynamo=True,
            external_data=False,
            verify=True,
        )


if __name__ == "__main__":
    main()
```

burn commit f5d81f61a8b38a0516487cf5588065a81c1e25cf


```
thread 'main' (91706) panicked at crates/burn-import/src/onnx/model_gen.rs:418:33:

lpips_squeeze.onnx': Type inference failed: InvalidAttribute { name: "ceil_mode", reason: "ceil_mode is not supported" }
```

**Comment by antimora** [comment]
Working on this issue
