### ISSUE TITLE
ONNX import regression: `Invalid shape for broadcasting - the dimension from the 2. to last position has conflicting values 3 and 32 from different inputs`

### ISSUE THREAD

**Issue by SimonBrandner** [tracel-ai/burn#2243]
```
ERROR burn_import::logger: PANIC => panicked at /home/simon/.cargo/git/checkouts/burn-178c6829f420dae1/6b51b73/crates/onnx-ir/src/dim_inference.rs:850:33:
Invalid shape for broadcasting - the dimension from the 2. to last position has conflicting values 3 and 32 from different inputs    
```

When updating burn in [my test repo](https://github.com/SimonBrandner/burn-import-testbed) to the newest commit (`6b51b73a5f8411332f90d1c60e4b8f88de0fe3db`) from `c94e7438293b1ce441f75fbed8dd651ff1b54b92`, I get this error

**Comment by laggui** [comment]
Broadcasting checks were added in #2213.

Seems like your test repo contains multiple models, can you point to the one with the flagged regression? Gotta identify which node with broadcasted input support is causing this error.

**Comment by SimonBrandner** [comment]
I believe it is this one: https://github.com/SimonBrandner/burn-import-testbed/blob/main/models/recognizer.onnx

**Comment by hexd0t** [comment]
I'm trying to look at your examples, but downloading the ONNX models fails with

```
> git lfs fetch
fetch: Fetching reference refs/heads/main
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/SimonBrandner/burn-import-testbed.git/info/lfs'
```

Are the models hosted somewhere else?

Can you tell which node is being evaluated by looking at the log before the panic (should be one of the [Ops capable of broadcasting](https://github.com/onnx/onnx/blob/main/docs/Broadcasting.md)), and take a look at the Input Tensor shapes using Netron, similar to the following screenshot:
<img width="364" alt="{43F42A54-463E-42B3-8E08-0A4D1A0549A2}" src="https://github.com/user-attachments/assets/78636547-269e-4b8e-bfc4-2e9e90672c6f">

According to the panic message, there are Tensors with different lengths > 1 for the same dimension, e.g., a Tensor [3, x, y] is broadcast together with a Tensor of shape [32, x, y], which is invalid according to ONNX spec (although the validation on import might also have a bug):

> In ONNX, a set of tensors are multidirectional broadcastable to the same shape if one of the following is true:
>
>    The tensors all have exactly the same shape.
    The tensors all have the same number of dimensions and the length of each dimensions is either a common length or 1.
    The tensors that have too few dimensions can have their shapes prepended with a dimension of length 1 to satisfy property 2.

**Comment by SimonBrandner** [comment]
Oh, sorry about that... I'll probably zip them at some point, Git LFS is a pain... The model can be downloaded from [here](https://drive.google.com/file/d/1ijbMt1LETLQc6GDGAtEJx8ggEGenyM7m/view?usp=sharing) but you might need to update the opset...

Let me know, if this is enough for you to proceed! (I can try to help further, if necessary, later)

**Comment by hexd0t** [comment]
Thanks for making it available, I can reproduce the error (the screenshot already has some debug info added):

<img width="715" alt="{76C349CA-245B-46BB-BE7C-A985E828DC06}" src="https://github.com/user-attachments/assets/f30f49aa-131d-4aa4-aa4a-416595324631">

Looking at the model in Netron, the Operation gets a valid input for broadcasting (just checking that the panic is actually a false positive):
<img width="227" alt="{6B0F4C32-D188-4A21-A4BC-A0AC3661F0CC}" src="https://github.com/user-attachments/assets/ff22e5ab-336f-4134-a601-ec7974aace4f">

Comparing the Shapes that are processed by the broadcast validation vs. those seen in Netron, it seems like the input values to the `dim_inference` step for the PRelu are already bad, and the recently added validation just exposes this problem - instead of a problem inside of the added check itself.

I'll see whether I can locate the source of the mismatched input shape; just wanted to post a status update / help others get started if they also want to take a look.

**Comment by ZOXEXIVO** [comment]
Same problem with importing Yolo v12 model

```
DEBUG onnx_ir::from_onnx: adding node "mul55"    
  DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Add"    
  DEBUG onnx_ir::from_onnx: renaming node "/model.6/Add"    
  ERROR burn_import::logger: PANIC => panicked at C:\Users\xxx\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\onnx-ir-0.16.0\src\dim_inference.rs:893:33:
  Invalid shape for broadcasting - the dimension from the 2. to last position has conflicting values 3 and 768 from different inputs    
  --- stderr
  thread 'main' panicked at C:\Users\xxx\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\onnx-ir-0.16.0\src\dim_inference.rs:893:33:
  Invalid shape for broadcasting - the dimension from the 2. to last position has conflicting values 3 and 768 from different inputs
```

**Comment by polarathene** [comment]
## Reproduction

For reference, using the current git version of Burn (_has some improvements since the latest release tag [`v0.17.1`](https://github.com/tracel-ai/burn/releases/tag/v0.17.1)_).

Reproduction uses [this `compose.yaml`](https://github.com/tracel-ai/burn/issues/1714#issuecomment-2952373124).

### `recognizer.onnx`

Original reported ONNX model builds/imports successfully:

```bash
ONNX_MODEL_URL='https://github.com/SimonBrandner/burn-import-testbed/raw/main/models/recognizer.onnx' \
docker compose run --rm -it burn-onnx-import cargo build
```

---

### YOLOv12

> Same problem with importing Yolo v12 model

You have not linked to a specific ONNX model file for testing.. I came across these:

```bash
# Variants: n,s,m,l,x
# https://github.com/sunsmarterjie/yolov12/releases/tag/seg
ONNX_MODEL_URL='https://github.com/sunsmarterjie/yolov12/releases/download/seg/yolov12n-seg.onnx' \
docker compose run --rm -it burn-onnx-import cargo build
```

```rust
  DEBUG burn_import::burn::graph: Registering node => 'matmul'
  ERROR burn_import::logger: PANIC => panicked at /root/.cargo/git/checkouts/burn-6c277d792b0d5d7a/1f5ccd4/crates/burn-import/src/burn/ty.rs:122:19:
  "/model.6/m.0/m.0.0/attn/Constant_17_output_0" is not a valid Ident
```

---

```bash
# Variants: n,s,m,l,x
# https://github.com/sunsmarterjie/yolov12/releases/tag/turbo
ONNX_MODEL_URL='https://github.com/sunsmarterjie/yolov12/releases/download/turbo/yolov12n.onnx' \
docker compose run --rm -it burn-onnx-import cargo build
```

```rust
  DEBUG burn_import::burn::graph: Registering node => 'matmul'
  ERROR burn_import::logger: PANIC => panicked at /root/.cargo/git/checkouts/burn-6c277d792b0d5d7a/1f5ccd4/crates/burn-import/src/burn/ty.rs:122:19:
  "/model.6/m.0/m.0.0/attn/Constant_17_output_0" is not a valid Ident
```

---

```bash
# Variants: n,s,m,l,x
# https://github.com/sunsmarterjie/yolov12/releases/tag/v1.0
ONNX_MODEL_URL='https://github.com/sunsmarterjie/yolov12/releases/download/v1.0/yolov12n.onnx' \
docker compose run --rm -it burn-onnx-import cargo build
```

```rust
  DEBUG burn_import::burn::graph: Registering node => 'transpose'
  ERROR burn_import::logger: PANIC => panicked at /root/.cargo/git/checkouts/burn-6c277d792b0d5d7a/1f5ccd4/crates/burn-import/src/burn/ty.rs:122:19:
  "/model.6/m.0/m.0.0/attn/Constant_6_output_0" is not a valid Ident
```

---

**UPDATE:** Error regarding invalid identifier:
- Has an existing issue here: https://github.com/tracel-ai/burn/issues/2878
- With PR addressing it here: https://github.com/tracel-ai/burn/pull/3208
- [The PR was tested](https://github.com/tracel-ai/burn/issues/600#issuecomment-3047401900) in it's current state where it ran into a failure.

**Comment by antimora** [comment]
ONNX import lives in tracel-ai/burn-onnx now, and the model was reported to import fine on a newer version. Closing. Please open an issue there if it still fails.
