### ISSUE TITLE
WGPU backend panic on android emulators <= 10

### ISSUE THREAD

**Issue by tkkcc** [tracel-ai/burn#2299]
**Describe the bug**
load model with wgpu backend panic on android emulators <=10. seems egl library path discovery issue. using ndarray backend is fine, higher android api is fine.

android 15 x86_64 (android studio emulator): fine
android 12.0 x86_64 (android studio emulator): fine

android 7.0 x86 (genymotion):
```txt
load_driver(/system/lib/egl/libGLES_emulation.so): dlopen failed: library "/system/lib/egl/libGLES_emulation.so" not found
thread '<unnamed>' panicked at 'No adapter found for graphics API AutoGraphicsApi': /home/bilabila/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cubecl-wgpu-0.2.0/src/runtime.rs:314
```
check libs:
```txt
1|genymotion:/ # ls /system/lib/egl/libGLES*
/system/lib/egl/libGLESv1_CM_emulation.so /system/lib/egl/libGLESv2_emulation.so
```

android 7.0 x86_64 (android studio emulator):
```
00:45:07.688  E  load_driver(/system/lib64/egl/libGLES_emulation.so): dlopen failed: library "/system/lib64/egl/libGLES_emulation.so" not found
00:45:07.697  E  log_panics: thread '<unnamed>' panicked at 'No adapter found for graphics API AutoGraphicsApi': /home/bilabila/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cubecl-wgpu-0.2.0/src/runtime.rs:314
```
check libs:
```
1|generic_x86_64:/ $ ls /system/lib64/egl/lib*
/system/lib64/egl/libEGL_emulation.so /system/lib64/egl/libGLES_android.so /system/lib64/egl/libGLESv1_CM_emulation.so /system/lib64/egl/libGLESv2_emulation.so
```

android 9.0 x86 (android studio emulator):
```txt
00:48:14.829  E  Could not load /vendor/lib/egl/libGLES_emulation.so from sphal namespace: dlopen failed: library "/vendor/lib/egl/libGLES_emulation.so" not found.
00:48:14.829  E  load_driver(/vendor/lib/egl/libGLES_emulation.so): unknown
00:48:14.856  E  log_panics: thread '<unnamed>' panicked at 'No adapter found for graphics API AutoGraphicsApi': /home/bilabila/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cubecl-wgpu-0.2.0/src/runtime.rs:314
```
check libs:
```txt
1|generic_x86_arm:/ $ ls /vendor/lib/egl/lib*
/vendor/lib/egl/libEGL_emulation.so   /vendor/lib/egl/libGLESv1_CM_emulation.so   /vendor/lib/egl/libGLESv2_emulation.so
/vendor/lib/egl/libEGL_swiftshader.so /vendor/lib/egl/libGLESv1_CM_swiftshader.so /vendor/lib/egl/libGLESv2_swiftshader.so
```
android 10.0 x86 (android studio emulator):
```
00:55:54.999  D  loaded /vendor/lib/egl/libEGL_emulation.so
00:55:55.000  D  loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
00:55:55.000  D  loaded /vendor/lib/egl/libGLESv2_emulation.so
00:55:55.055  E  log_panics: thread '<unnamed>' panicked at 'No adapter found for graphics API AutoGraphicsApi': /home/bilabila/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cubecl-wgpu-0.2.0/src/runtime.rs:314
```
check libs:
```
generic_x86:/ $ ls /vendor/lib/egl/lib*
/vendor/lib/egl/libEGL_emulation.so   /vendor/lib/egl/libGLESv1_CM_emulation.so   /vendor/lib/egl/libGLESv2_emulation.so
/vendor/lib/egl/libEGL_swiftshader.so /vendor/lib/egl/libGLESv1_CM_swiftshader.so /vendor/lib/egl/libGLESv2_swiftshader.so
```

**To Reproduce**
run onnx example on android studio emulators, change backend from NdArray<f32> to Wgpu<f32>, like
```sh
type Backend = Wgpu<f32>;
let device = <Backend as burn::tensor::backend::Backend>::Device::default();
let model: Model<Backend> = Model::from_file("/data/local/tmp/mnist", &Default::default());
```

**Expected behavior**
no panic

**Comment by antimora** [comment]
Reported against cubecl-wgpu 0.2 on old Android emulators. Closing as outdated. Please open a new issue if it reproduces on a recent version.
