### ISSUE TITLE
CUDA-JIT: Invalid value for --gpu-architecture

### ISSUE THREAD

**Issue by rubenjr0** [tracel-ai/burn#2453]
**Describe the bug**

The `CudaJit` backend produces a panic on startup on 0.15 and main:

```
thread 'main' panicked at /home/USER/.cargo/git/checkouts/cubecl-aa41a28b39b598f9/0dff475/crates/cubecl-cuda/src/compute/server.rs:328:17:
[Compilation Error]
    nvrtc: error: invalid value for --gpu-architecture (-arch)
[Source]
typedef unsigned int uint;

struct __align__(32) float_8 {
    float i_0;
    float i_1;
    float i_2;
    float i_3;
    float i_4;
    float i_5;
    float i_6;
    float i_7;
};


extern "C" __global__ void kernel(
float_8 output_0[],float_8 output_1[],uint info[]
) {

    int3 absoluteIdx = make_int3(
        blockIdx.x * blockDim.x + threadIdx.x,
        blockIdx.y * blockDim.y + threadIdx.y,
        blockIdx.z * blockDim.z + threadIdx.z
    );

    uint idxGlobal = (absoluteIdx.z * gridDim.x * blockDim.x * gridDim.y * blockDim.y) + (absoluteIdx.y * gridDim.x * blockDim.x) + absoluteIdx.x;
uint rank = info[0];
uint rank_2 = rank * 2;
uint l_0_0;
bool l_0_1;
float l_0_2;
float l_0_3;
l_0_0 = info[(2 * 2 * info[0]) + 1] / 8;
l_0_1 = idxGlobal < l_0_0;
if (l_0_1) {
l_0_0 = uint(0);
l_0_2 = float(l_0_0);
l_0_0 = uint(1);
l_0_3 = float(l_0_0);
output_0[idxGlobal] = float_8{
float(l_0_2),
float(l_0_2),
float(l_0_2),
float(l_0_2),
float(l_0_2),
float(l_0_2),
float(l_0_2),
float(l_0_2),
};
output_1[idxGlobal] = float_8{
float(l_0_3),
float(l_0_3),
float(l_0_3),
float(l_0_3),
float(l_0_3),
float(l_0_3),
float(l_0_3),
float(l_0_3),
};
}

}
```

**To Reproduce**
 1. Use the `cuda-jit` feature
 2. Use the `CudaJit` backend
 3. Attempt to run

**Desktop:**
 - OS: Pop!_OS 22.04
 - GPU: NVIDIA GeForce RTX 4060 Ti

**Comment by nathanielsimard** [comment]
Somehow that returns an invalid arch https://github.com/tracel-ai/cubecl/blob/3c7fb12a14a8df2c20b4fcca6e5a7b1396c91b7e/crates/cubecl-cuda/src/runtime.rs#L40

**Comment by laggui** [comment]
@rubenjr0 is this still an issue?

**Comment by rubenjr0** [comment]
Yes, I can confirm it is still an issue. I ran `cargo update` to fetch the latest version of burn and still got:

```
thread 'main' panicked at /home/MYUSER/.cargo/git/checkouts/cubecl-aa41a28b39b598f9/2c09d4d/crates/cubecl-cuda/src/compute/server.rs:380:17:
[Compilation Error]
    nvrtc: error: invalid value for --gpu-architecture (-arch)
```

**Comment by nathanielsimard** [comment]
The architecture is fetch that way:

```rust
let arch = unsafe {
        let major = cudarc::driver::result::device::get_attribute(
            device_ptr,
            cudarc::driver::sys::CUdevice_attribute::CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR,
        )
        .unwrap();
        let minor = cudarc::driver::result::device::get_attribute(
            device_ptr,
            cudarc::driver::sys::CUdevice_attribute::CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR,
        )
        .unwrap();
        major * 10 + minor
    } as u32;

```

So if the major is 7 and the minor is 8, we will have 78 as the arch version. Maybe there is a bug if the minor is > 10.

**Comment by oscarbroddegard** [comment]
Bringing this up again since I'm getting a similar error message when allocating a tensor. Has this issue been resolved? If so what was the conclusion?

## Output
```
thread 'main' panicked at /home/USER/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/burn-cubecl-fusion-0.20.0/src/optim/elemwise/optimization.rs:44:17:
RunnerError(A compilation error happened during launch
Caused by:
  An error caused the compilation to fail
Caused by:
  [Compilation Error] 
    nvrtc: error: invalid value for --gpu-architecture (-arch)

// kernel omitted to avoid verbosity

Backtrace:
No backtrace available) - FuseTrace { blocks: [FuseBlock { settings: FuseSettings { broadcast: true, output_shape_updates: true, inplace: true, vectorization: Activated, ref_layout: Any }, ops: [Assign(UnaryFuseArgs { input: Literal(0, F32), out: Local(0, F32) })], shape_ref: [0, 1, 2, 3], reads: {}, writes: {TensorId { value: 0 }: Assign(UnaryFuseArgs { input: Local(0, F32), out: Output(0, F32, Unknown) })} }], resources: FuseResources { outputs: RegisteredTensors { tensors: [Normal(TensorIr { id: TensorId { value: 0 }, shape: Shape { dims: [0, 1, 2, 3] }, status: NotInit, dtype: F32 }, F32)] }, inputs: RegisteredTensors { tensors: [] }, scalars: [], views: [], indexed: {}, inputs_unhandled: [], outputs_unhandled: [], num_reshaped: 0, dropped: {} } }
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: burn_cubecl::fusion::<impl burn_fusion::backend::Optimization<burn_cubecl::fusion::FusionCubeRuntime<R,BT>> for burn_cubecl_fusion::optim::base::CubeOptimization<R>>::execute
   3: burn_fusion::stream::execution::ordering::OrderedExecution<R>::execute_optimization
   4: burn_fusion::stream::queue::execution::QueueExecution<R>::execute_strategy
   5: burn_fusion::stream::queue::execution::QueueExecution<R>::run
   6: <burn_fusion::stream::multi::Segment<R> as burn_fusion::stream::execution::processor::StreamSegment<<R as burn_fusion::backend::FusionRuntime>::Optimization>>::execute
   7: burn_fusion::stream::execution::processor::Processor<O>::process
   8: burn_fusion::stream::multi::MultiStream<R>::drain
   9: burn_fusion::client::GlobalFusionClient<R>::resolve_tensor_float
```

## System:
OS: Ubuntu 24.04
GPU: RTX 5070 (Laptop GPU)
CUDA: 13.1

---

Is compute capability 12.0 and higher not supported, or is the issue with something else?

**Comment by laggui** [comment]
> Is compute capability 12.0 and higher not supported, or is the issue with something else?

It should be! We had some benchmarks for the 5090.

I suspect the issue stems from [this code in `cubecl-cuda`](https://github.com/tracel-ai/cubecl/blob/main/crates/cubecl-cuda/src/compute/context.rs#L125-L129):
```rust
let arch = if self.arch.version >= 90 {
    format!("--gpu-architecture=sm_{}a", self.arch)
} else {
    format!("--gpu-architecture=sm_{}", self.arch)
};
```

so your NVRTC version doesn't appear to recognize the `sm_120a` architecture which leverages specialized accelerated features. It should technically be supported though.

What does `nvcc --version` report?

**Comment by oscarbroddegard** [comment]
Ok, thanks @laggui! 

`nvcc --version` yields 
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Wed_Aug_20_01:58:59_PM_PDT_2025
Cuda compilation tools, release 13.0, V13.0.88
Build cuda_13.0.r13.0/compiler.36424714_0
```

and `nvidia-smi --version`

```
NVIDIA-SMI version  : 590.48.01
NVML version        : 590.48
DRIVER version      : 590.48.01
CUDA Version        : 13.1
```

To me, it looks like there is a discrepancy between the CUDA version perceived by `nvcc` and `nvidia-smi`, not sure if it's relevant. Running (and compiling) kernels for/with CUDA has worked fine through other tools so far.

**Comment by laggui** [comment]
Hmmm ok, version 13.0 should be sufficient. But it could be a nvrtc library version mismatch. Do you possibly have multiple versions installed on your system? It might be loading an older version of the `libnvrtc` library that doesn't recognize that architecture 🤔 

Could check the exact lib version with `ls -l /usr/local/cuda/lib64/libnvrtc.so.*` and the linker path via `ldconfig -p | grep nvrtc`.

And if the versions are compatible, then perhaps there's a bug and the code doesn't actually resolve to `sm_120a` for the provided  `--gpu-architecture`.

**Comment by oscarbroddegard** [comment]
The linker looks to be finding multiple versions! `ldconfig -p | grep nvrtc` yields 
```
libnvrtc.so.13 (libc6,x86-64) => /usr/local/cuda/targets/x86_64-linux/lib/libnvrtc.so.13
libnvrtc.so.13 (libc6,x86-64) => /usr/local/cuda-13.0/targets/x86_64-linux/lib/libnvrtc.so.13
libnvrtc.so.12 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvrtc.so.12
libnvrtc.so (libc6,x86-64) => /usr/local/cuda/targets/x86_64-linux/lib/libnvrtc.so
libnvrtc.so (libc6,x86-64) => /usr/local/cuda-13.0/targets/x86_64-linux/lib/libnvrtc.so
libnvrtc.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvrtc.so
libnvrtc.alt.so.13 (libc6,x86-64) => /usr/local/cuda-13.0/targets/x86_64-linux/lib/libnvrtc.alt.so.13
libnvrtc.alt.so (libc6,x86-64) => /usr/local/cuda-13.0/targets/x86_64-linux/lib/libnvrtc.alt.so
libnvrtc-builtins.so.13.1 (libc6,x86-64) => /usr/local/cuda/targets/x86_64-linux/lib/libnvrtc-builtins.so.13.1
libnvrtc-builtins.so.13.0 (libc6,x86-64) => /usr/local/cuda-13.0/targets/x86_64-linux/lib/libnvrtc-builtins.so.13.0
libnvrtc-builtins.so.12.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvrtc-builtins.so.12.0
libnvrtc-builtins.so (libc6,x86-64) => /usr/local/cuda/targets/x86_64-linux/lib/libnvrtc-builtins.so
libnvrtc-builtins.so (libc6,x86-64) => /usr/local/cuda-13.0/targets/x86_64-linux/lib/libnvrtc-builtins.so
libnvrtc-builtins.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvrtc-builtins.so
libnvrtc-builtins.alt.so.13.0 (libc6,x86-64) => /usr/local/cuda-13.0/targets/x86_64-linux/lib/libnvrtc-builtins.alt.so.13.0
libnvrtc-builtins.alt.so (libc6,x86-64) => /usr/local/cuda-13.0/targets/x86_64-linux/lib/libnvrtc-builtins.alt.so
```
which to me looks like there's maybe a CUDA 12.x lib at `/lib/x86_64-linux-gnu`?

**Comment by laggui** [comment]
Obviously it will depend what version shows up for the linker first, but that setup looks like a good conflict candidate 😅 

You could make sure the latest version is detected and used by setting your `LD_LIBRARY_PATH`.

Hopefully that is the issue, keep us posted!

**Comment by oscarbroddegard** [comment]
Problem was solved by purging the `libnvrtc` files from the dir where the .12 version was found by the linker! Sometimes the brute force solution is the best one I guess. Thanks for the support @laggui :D

**Comment by laggui** [comment]
Happy to hear!

I have a feeling the original issue was similar. Will close for now, but feel free to re-open or open a new issue if required.
