### ISSUE TITLE
`unsqueeze_dims()` example panic

### ISSUE THREAD

**Issue by relf** [tracel-ai/burn#2493]
**Describe the bug**
I get a panic error with `source slice length (3) does not match destination slice length (4)` message when running `unsqueeze_dims()` example. 

**To Reproduce**
```rust
use burn::backend::{ndarray::NdArrayDevice, NdArray};
use burn_tensor::{Shape, Tensor};

fn main() {
    let device = NdArrayDevice::Cpu;
    let tensor = Tensor::<NdArray, 3>::ones(Shape::new([3, 4, 5]), &device);
    // Unsqueeze the leading dimension (0) once and the trailing dimension (-1) twice.
    // The resulting tensor will have dimensions [1, 3, 4, 5, 1, 1].
    let unsqueezed: Tensor<NdArray, 6> = tensor.unsqueeze_dims(&[0, -1, -1]);
    println!("{unsqueezed:?}");
}
```

with
```
[package]
name = "bug_unsqueeze_dims"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.15.0", features = ["ndarray"] }
burn-tensor = "0.15.0"
```

**Expected behavior**
No panic error

**Observed behavior**
```
>cargo run
   Compiling bug_unsqueeze_dims v0.1.0 (D:\rlafage\workspace\bug_unsqueeze_dims)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 3.29s
     Running `target\debug\bug_unsqueeze_dims.exe`
thread 'main' panicked at D:\rlafage\.cargo\registry\src\index.crates.io-6f17d22bba15001f\burn-tensor-0.15.0\src\tensor\api\base.rs:560:44:
source slice length (3) does not match destination slice length (4)
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:665
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\panicking.rs:74
   2: core::slice::impl$0::copy_from_slice::len_mismatch_fail
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\slice\mod.rs:3674
   3: core::slice::impl$0::copy_from_slice<usize>
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\slice\mod.rs:3681
   4: burn_tensor::tensor::api::base::impl$1::unsqueeze_dims::closure$1<burn_ndarray::backend::NdArray<f32,i64,i8>,3,burn_tensor::tensor::api::kind::Float,6>
             at D:\rlafage\.cargo\registry\src\index.crates.io-6f17d22bba15001f\burn-tensor-0.15.0\src\tensor\api\base.rs:560
   5: core::slice::iter::impl$182::for_each<usize,burn_tensor::tensor::api::base::impl$1::unsqueeze_dims::closure_env$1<burn_ndarray::backend::NdArray<f32,i64,i8>,3,burn_tensor::tensor::api::kind::Float,6> >
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\slice\iter\macros.rs:254
   6: burn_tensor::tensor::api::base::Tensor<burn_ndarray::backend::NdArray<f32,i64,i8>,3,burn_tensor::tensor::api::kind::Float>::unsqueeze_dims<burn_ndarray::backend::NdArray<f32,i64,i8>,3,burn_tensor::tensor::api::kind::Float,6>
             at D:\rlafage\.cargo\registry\src\index.crates.io-6f17d22bba15001f\burn-tensor-0.15.0\src\tensor\api\base.rs:551
   7: bug_unsqueeze_dims::main
             at .\src\main.rs:9
   8: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\ops\function.rs:250
   9: core::hint::black_box
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\hint.rs:389
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\bug_unsqueeze_dims.exe` (exit code: 101)
```

**Desktop (please complete the following information):**
 - OS: Windows10

**Comment by laggui** [comment]
Thanks for flagging that! 🙏 I just submitted a PR that should fix the issue.
