### ISSUE TITLE
burn-jit wgpu test errors (1.83.0 ; 24.04.1 LTS;  CUDA 12; nvidia-driver 550)

### ISSUE THREAD

**Issue by crutcher** [tracel-ai/burn#2570]
**Describe the bug**
```
$ ./run-checks.sh std
...
---- tests::jit::tensor::f32_ty::remainder::tests::should_have_no_remainder stdout ----
thread 'tests::jit::tensor::f32_ty::remainder::tests::should_have_no_remainder' panicked at crates/burn-wgpu/src/lib.rs:113:5:
Tensors are not approx eq:
  => Position 4: 0.5034000277519226 != 0 | difference 0.5034000277519226 > tolerance 0.0010000000000000002

---- tests::jit_fusion::tensor::f32_ty::remainder::tests::should_have_no_remainder stdout ----
thread 'tests::jit_fusion::tensor::f32_ty::remainder::tests::should_have_no_remainder' panicked at crates/burn-wgpu/src/lib.rs:113:5:
Tensors are not approx eq:
  => Position 4: 0.5034000277519226 != 0 | difference 0.5034000277519226 > tolerance 0.0010000000000000002
```

**To Reproduce**
Details:
 
toolchain - 1.83.0
git - 3dc4b43e92ec5683ca39c194acf274b131d44dfa
ubuntu - 24.04.1 LTS
Cards - 2x NVIDIA GeForce RTX 3090
nvidia libs - listed below

**Comment by antimora** [comment]
Outdated
