### ISSUE TITLE
Impossible to import ONNX model 

### ISSUE THREAD

**Issue by anagaev** [tracel-ai/burn#2592]
Hi all!

I tried to use an .onnx model from Hugging Face with burn when I found this potential issues. 

**Describe the bug**
One node (`Where` to be precise) throw error:
```
ERROR burn_import::logger: PANIC => panicked at crates/onnx-ir/src/dim_inference.rs:821:5:
assertion `left == right` failed: Where x and y have different element types!
  left: Int64
 right: Float32
```
After debugging I found that one of the previous node ( `Unsqueeze` ) took two Int64 input arguments and return a Float32 tensor. So, it causes the error above and doesn't correspond to onnx graph from Netron.

**To Reproduce**
1) Download the .onnx model from [HuggingFace](https://huggingface.co/onnx-community/depth-anything-v2-small/blob/main/onnx/model.onnx) (also tried with [this model](https://huggingface.co/onnx-community/dpt-dinov2-small-kitti/blob/main/onnx/model.onnx))
2) Following instruction for [_Importing ONNX Models in Burn_](https://burn.dev/burn-book/import/onnx-model.html#importing-onnx-models-in-burn) 
3) Build the project and see the error.

**Expected behavior**
Correct import from .onnx files.

**Screenshots**
![screeen](https://github.com/user-attachments/assets/24d81a9a-6337-4061-bd75-1ee1687885de)

**Desktop (please complete the following information):**
 - OS: archlinux 6.12.1-arch1-1 
 - Version: rustc 1.83.0
```
 [dependencies]
burn = "0.15.0"
burn-ndarray = "0.15.0"

[build-dependencies]
burn-import = "~0.15"
```

**Potential fixing**
It seems the type [here](https://github.com/tracel-ai/burn/blob/6dbc3fd295c8c84009f32c012f4161bd81106b73/crates/onnx-ir/src/proto_conversion.rs#L193) which is default right now should match the type of the inputs.

**Comment by anagaev** [comment]
I think `ArgType::Tensor(tensor) => tensor.elem_type.clone(),` should be `ArgType::Tensor(_) => node.inputs[1].ty.elem_type().clone(),` [here](https://github.com/tracel-ai/burn/blob/6dbc3fd295c8c84009f32c012f4161bd81106b73/crates/onnx-ir/src/dim_inference.rs#L495) in order to match input type.

If it seems ok, I could do a pr.

Anyway, importing the onnx model doesn't work correctly even after this change because of another node (`Slice`). Output shape isn't correct.
@laggui would be better to continue discussion here or create a new bug report for `Slice`?

**Comment by laggui** [comment]
> I think `ArgType::Tensor(tensor) => tensor.elem_type.clone(),` should be `ArgType::Tensor(_) => node.inputs[1].ty.elem_type().clone(),` [here](https://github.com/tracel-ai/burn/blob/6dbc3fd295c8c84009f32c012f4161bd81106b73/crates/onnx-ir/src/dim_inference.rs#L495) in order to match input type.

Hmm hat doesn't seem correct either, the `node.inputs[1]` doesn't represent the input data but rather the axis. But the output type should match the input type 🙂

> If it seems ok, I could do a pr.

We're always opened to PRs!

> Anyway, importing the onnx model doesn't work correctly even after this change because of another node (`Slice`). Output shape isn't correct. @laggui would be better to continue discussion here or create a new bug report for `Slice`?

We can keep the same issue open to represent your ONNX model.

I know there are many things that are far from perfect with the current ONNX import approach, but iirc @antimora was working on some improvements recently

**Comment by anagaev** [comment]
@laggui thank you for your replay!
 Ok, I'm continuing posting bug reports here 
 I thought node.inputs[0] was the axis... I'll check it again

**Comment by anagaev** [comment]
A potential issue with `Slice`

**Describe the bug**
The output shape of the node `Slice` is always the same as the input shape. If the arguments `starts`, `ends`, `steps` are arbitrary, the output shape can differ.

**To Reproduce**
1. Load a .onnx model with `Slice` node that return a smaller slice of the input data (e.g. each value of `steps` > 1). [The model](https://huggingface.co/onnx-community/depth-anything-v2-small/blob/main/onnx/model.onnx) I mentioned above contains this `Slice` node. 
2. Following instruction for [Importing ONNX Models in Burn](https://burn.dev/burn-book/import/onnx-model.html#importing-onnx-models-in-burn)
3. Compare the output dimension and shape of this node from Netron and  Burn. 

**Expected behavior**
The node uses `starts`, `ends`, `steps` to correctly set the output shape.

**Screenshots**
![2024-12-12_15-27](https://github.com/user-attachments/assets/1a6cbfa1-30cb-4f51-8587-a065bbffa474)


**Desktop (please complete the following information):**
- OS: archlinux 6.12.1-arch1-1
- Version: rustc 1.83.0

**Additional context**
This issue clearly affects inputs of `ArgType::Shape`. If I'm not mistaken, in this case all shapes and values (`data`, `starts`, `ends`, `Optional(steps)`) are defined. So, it's possible to correctly define the output shape during model building. 
The shape of `ArgType::Tensor` is defined during runtime (correct me please, if I'm wrong). So, it's simply possible to set `ArgType::Tensor.shape` as `None`

**Comment by polarathene** [comment]
## Reproduction

For reference, using the current git version of Burn (_has some improvements since the latest release tag [`v0.17.1`](https://github.com/tracel-ai/burn/releases/tag/v0.17.1)_).

Reproduction uses [this `compose.yaml`](https://github.com/tracel-ai/burn/issues/1714#issuecomment-2952373124).

### `dpt-dinov2-small-kitti`

```bash
ONNX_MODEL_URL=https://huggingface.co/onnx-community/dpt-dinov2-small-kitti/resolve/main/onnx/model.onnx \
docker compose run --rm -it burn-onnx-import cargo build
```

```rust
   INFO onnx_ir::from_onnx: Parsing ONNX file: src/model/example.onnx
  ERROR burn_import::logger: PANIC => panicked at /root/.cargo/git/checkouts/burn-6c277d792b0d5d7a/1f5ccd4/crates/onnx-ir/src/from_onnx.rs:381:5:
  Nodes are not topologically sorted
```

---

### `depth-anything-v2-small`

```bash
ONNX_MODEL_URL=https://huggingface.co/onnx-community/depth-anything-v2-small/resolve/main/onnx/model.onnx \
docker compose run --rm -it burn-onnx-import cargo build
```

```rust
  DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Expand"
  DEBUG onnx_ir::from_onnx: renaming node "/Expand"
  DEBUG onnx_ir::from_onnx: checking node expand1 for constants
  DEBUG onnx_ir::from_onnx: checking input Argument { name: "where1_out1", ty: Tensor(TensorType { elem_type: Int64, rank: 1, static_shape: None }), value: None, passed: false } for const
  DEBUG onnx_ir::rank_inference: Inferring rank for node: expand1
  ERROR burn_import::logger: PANIC => panicked at /root/.cargo/git/checkouts/burn-6c277d792b0d5d7a/1f5ccd4/crates/onnx-ir/src/node/expand.rs:40:18:
  Shape input must have a static shape defined
```

**Comment by antimora** [comment]
Currently is failing with this error: 

DEBUG onnx_ir::rank_inference: Inferring rank for node: expand1
DEBUG onnx_ir::node::expand: Expand node expand1 has 2 inputs
DEBUG onnx_ir::node::expand: Expand node expand1 input[0]: Tensor(TensorType { elem_type: Float32, rank: 3, static_shape: Some([1, 1, 384]) })
DEBUG onnx_ir::node::expand: Expand node expand1 input[1]: Tensor(TensorType { elem_type: Int64, rank: 1, static_shape: None })   
 WARN onnx_ir::node::expand: Expand node expand1 has dynamic shape tensor without static shape info. Using output rank if available.
ERROR burn_import::logger: PANIC => panicked at crates/onnx-ir/src/node/expand.rs:89:38:
Cannot determine output rank for Expand node expand1 with fully dynamic shape tensor. Please provide static shape or use Shape type.

thread 'main' panicked at crates/onnx-ir/src/node/expand.rs:89:38:
Cannot determine output rank for Expand node expand1 with fully dynamic shape tensor. Please provide static shape or use Shape type.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
(onnx-tests) [bur

**Comment by antimora** [comment]
dpt-dinov2-small-kitti ONNX model is now convertible by burn-import. Need to upgrade to opset 16 using //burn.dev/books/burn/import/onnx-model.html instructions.


<img width="751" height="497" alt="Image" src="https://github.com/user-attachments/assets/4af707f3-09fa-49f2-ac45-9106e80a6b32" />
