### ISSUE TITLE
Load `yolov8` network into `burn-rs`

### ISSUE THREAD

**Issue by Luni-4** [tracel-ai/burn#675]
[Ultralytics](https://ultralytics.com) [YOLOv8](https://github.com/ultralytics/ultralytics) is a cutting-edge, state-of-the-art (SOTA) model that builds upon the success of previous YOLO versions and introduces new features and improvements to further boost performance and flexibility. YOLOv8 is designed to be fast, accurate, and easy to use, making it an excellent choice for a wide range of object detection and tracking, instance segmentation, image classification and pose estimation tasks.

[yolov8n.zip](https://github.com/burn-rs/burn/files/12411142/yolov8n.zip) contains `ONNX` model

![yolov8n onnx](https://github.com/burn-rs/burn/assets/12353765/a2f97ad5-55dc-4b11-9169-a1da248e3b85)

Missing operators:
- [x] Gather
- [x] Resize
- [x] Reshape
- [x] Split

**Comment by antimora** [comment]
I am working on a refactor or clean up of ONNX data. After I'll be working on Gather. Reshape should be already available. I checked in ONNX test for it.

**Comment by Luni-4** [comment]
Thank you @antimora! Yep, you're right, `Reshape` is already implemented

**Comment by Luni-4** [comment]
https://github.com/tracel-ai/burn/commit/37822fdb51a21acff20bae6a9dce24aced0cf575 closes this issue

**Comment by laggui** [comment]
@Luni-4 cool! Have you tried to load the model to see if everything is correctly supported?

**Comment by Luni-4** [comment]
This issue had been thought for missing operators, which are now all implemented, but you are right, the model does not load correctly. I've used the current `main` branch. Here's the error:

<details>
<summary>
Complete log
</summary>
<br />

```rust
 INFO burn_import::onnx::to_burn: Starting to convert ONNX to Burn
DEBUG burn_import::onnx::to_burn: Output directory: "./out"
 INFO burn_import::onnx::to_burn: Converting "../../../Downloads/yolov8n.onnx"
DEBUG burn_import::onnx::to_burn: Input file name: "yolov8n"
DEBUG burn_import::onnx::to_burn: Output file: "./out/yolov8n"
 INFO burn_import::onnx::to_burn: Generating model from "../../../Downloads/yolov8n.onnx"
DEBUG burn_import::onnx::to_burn: Development mode: true
DEBUG burn_import::onnx::to_burn: Output file: "./out/yolov8n"
 INFO onnx_ir::from_onnx: Parsing ONNX file: ../../../Downloads/yolov8n.onnx
DEBUG onnx_ir::from_onnx: Number of nodes: 259
DEBUG onnx_ir::from_onnx: Number of inputs: 1
DEBUG onnx_ir::from_onnx: Number of initializers: 127
DEBUG onnx_ir::from_onnx: Number of outputs: 1
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Conv"
DEBUG onnx_ir::from_onnx: renaming node "/model.0/conv/Conv"
DEBUG onnx_ir::from_onnx: checking node conv2d1 for constants
DEBUG onnx_ir::from_onnx: checking input Argument { name: "model.0.conv.weight", ty: Tensor(TensorType { elem_type: Float32, dim: 4, shape: Some([16, 3, 3, 3]) }), value: Some(Float32s([-2.0546875, -0.18859863, 1.90625, -6.5625, 0.5961914, 6.90625, -6.0117188, ...])), passed: false } for const
DEBUG onnx_ir::from_onnx: checking input Argument { name: "model.0.conv.bias", ty: Tensor(TensorType { elem_type: Float32, dim: 1, shape: Some([16]) }), value: Some(Float32s([1.3603516, 2.875, 1.5947266, 1.5214844, 6.7148438, 1.3818359, 4.3203125, ...])), passed: false } for const
DEBUG onnx_ir::from_onnx: adding node "conv2d1"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Sigmoid"
DEBUG onnx_ir::from_onnx: renaming node "/model.0/act/Sigmoid"
DEBUG onnx_ir::from_onnx: adding node "sigmoid1"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Mul"
DEBUG onnx_ir::from_onnx: renaming node "/model.0/act/Mul"
DEBUG onnx_ir::from_onnx: adding node "mul1"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Conv"
DEBUG onnx_ir::from_onnx: renaming node "/model.1/conv/Conv"
DEBUG onnx_ir::from_onnx: checking node conv2d2 for constants
DEBUG onnx_ir::from_onnx: checking input Argument { name: "model.1.conv.weight", ty: Tensor(TensorType { elem_type: Float32, dim: 4, shape: Some([32, 16, 3, 3]) }), value: Some(Float32s([-0.06317139, -0.25390625, -0.54833984, 0.066101074, 0.08123779, 0.72509766, 0.03213501, ...])), passed: false } for const
DEBUG onnx_ir::from_onnx: checking input Argument { name: "model.1.conv.bias", ty: Tensor(TensorType { elem_type: Float32, dim: 1, shape: Some([32]) }), value: Some(Float32s([0.83496094, 0.13500977, 4.2421875, 0.1315918, -0.58154297, 1.4902344, 2.6269531, ...])), passed: false } for const
DEBUG onnx_ir::from_onnx: adding node "conv2d2"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Sigmoid"
DEBUG onnx_ir::from_onnx: renaming node "/model.1/act/Sigmoid"
DEBUG onnx_ir::from_onnx: adding node "sigmoid2"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Mul"
DEBUG onnx_ir::from_onnx: renaming node "/model.1/act/Mul"
DEBUG onnx_ir::from_onnx: adding node "mul2"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Conv"
DEBUG onnx_ir::from_onnx: renaming node "/model.2/cv1/conv/Conv"
DEBUG onnx_ir::from_onnx: checking node conv2d3 for constants
DEBUG onnx_ir::from_onnx: checking input Argument { name: "model.2.cv1.conv.weight", ty: Tensor(TensorType { elem_type: Float32, dim: 4, shape: Some([32, 32, 1, 1]) }), value: Some(Float32s([0.020202637, 0.053497314, -0.023925781, -0.07409668, -0.045410156, 0.023269653, 0.069885254, ...])), passed: false } for const
DEBUG onnx_ir::from_onnx: checking input Argument { name: "model.2.cv1.conv.bias", ty: Tensor(TensorType { elem_type: Float32, dim: 1, shape: Some([32]) }), value: Some(Float32s([2.8769531, 1.6123047, 1.3994141, 2.9140625, 1.5839844, 3.7949219, -0.51464844, ...])), passed: false } for const
DEBUG onnx_ir::from_onnx: adding node "conv2d3"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Sigmoid"
DEBUG onnx_ir::from_onnx: renaming node "/model.2/cv1/act/Sigmoid"
DEBUG onnx_ir::from_onnx: adding node "sigmoid3"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Mul"
DEBUG onnx_ir::from_onnx: renaming node "/model.2/cv1/act/Mul"
DEBUG onnx_ir::from_onnx: adding node "mul3"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Split"
DEBUG onnx_ir::from_onnx: renaming node "/model.2/Split"
DEBUG onnx_ir::from_onnx: adding node "split1"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Conv"
DEBUG onnx_ir::from_onnx: renaming node "/model.2/m.0/cv1/conv/Conv"
DEBUG onnx_ir::from_onnx: checking node conv2d4 for constants
DEBUG onnx_ir::from_onnx: checking input Argument { name: "model.2.m.0.cv1.conv.weight", ty: Tensor(TensorType { elem_type: Float32, dim: 4, shape: Some([16, 16, 3, 3]) }), value: Some(Float32s([-0.0692749, 0.009162903, 0.041137695, -0.13903809, -0.25756836, -0.060638428, -0.08898926, ...])), passed: false } for const
DEBUG onnx_ir::from_onnx: checking input Argument { name: "model.2.m.0.cv1.conv.bias", ty: Tensor(TensorType { elem_type: Float32, dim: 1, shape: Some([16]) }), value: Some(Float32s([1.8271484, 3.9492188, 2.0332031, 3.1132813, 3.2929688, 2.8730469, -5.1289063, ...])), passed: false } for const
DEBUG onnx_ir::from_onnx: adding node "conv2d4"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Sigmoid"
DEBUG onnx_ir::from_onnx: renaming node "/model.2/m.0/cv1/act/Sigmoid"
DEBUG onnx_ir::from_onnx: adding node "sigmoid4"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Mul"
DEBUG onnx_ir::from_onnx: renaming node "/model.2/m.0/cv1/act/Mul"
DEBUG onnx_ir::from_onnx: adding node "mul4"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Conv"
DEBUG onnx_ir::from_onnx: renaming node "/model.2/m.0/cv2/conv/Conv"
DEBUG onnx_ir::from_onnx: checking node conv2d5 for constants
DEBUG onnx_ir::from_onnx: checking input Argument { name: "model.2.m.0.cv2.conv.weight", ty: Tensor(TensorType { elem_type: Float32, dim: 4, shape: Some([16, 16, 3, 3]) }), value: Some(Float32s([-0.010246277, -0.09918213, -0.04260254, 0.022415161, 0.26660156, 0.059295654, -0.026519775, ...])), passed: false } for const
DEBUG onnx_ir::from_onnx: checking input Argument { name: "model.2.m.0.cv2.conv.bias", ty: Tensor(TensorType { elem_type: Float32, dim: 1, shape: Some([16]) }), value: Some(Float32s([1.5976563, 1.5966797, 3.5332031, -1.4785156, 1.7324219, -1.6542969, 5.2734375, ...])), passed: false } for const
DEBUG onnx_ir::from_onnx: adding node "conv2d5"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Sigmoid"
DEBUG onnx_ir::from_onnx: renaming node "/model.2/m.0/cv2/act/Sigmoid"
DEBUG onnx_ir::from_onnx: adding node "sigmoid5"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Mul"
DEBUG onnx_ir::from_onnx: renaming node "/model.2/m.0/cv2/act/Mul"
DEBUG onnx_ir::from_onnx: adding node "mul5"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Add"
DEBUG onnx_ir::from_onnx: renaming node "/model.2/m.0/Add"
DEBUG onnx_ir::dim_inference: Input 0 has no known shape, cannot predict broadcast result shape
DEBUG onnx_ir::from_onnx: adding node "add1"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Concat"
DEBUG onnx_ir::from_onnx: renaming node "/model.2/Concat"
DEBUG onnx_ir::from_onnx: adding node "concat1"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Conv"
DEBUG onnx_ir::from_onnx: renaming node "/model.2/cv2/conv/Conv"
DEBUG onnx_ir::from_onnx: checking node conv2d6 for constants
DEBUG onnx_ir::from_onnx: checking input Argument { name: "model.2.cv2.conv.weight", ty: Tensor(TensorType { elem_type: Float32, dim: 4, shape: Some([32, 48, 1, 1]) }), value: Some(Float32s([-0.028778076, 0.0006098747, -0.08135986, -0.0025787354, 0.027069092, 0.016616821, 0.031677246, ...])), passed: false } for const
DEBUG onnx_ir::from_onnx: checking input Argument { name: "model.2.cv2.conv.bias", ty: Tensor(TensorType { elem_type: Float32, dim: 1, shape: Some([32]) }), value: Some(Float32s([1.0126953, 2.5234375, 3.3945313, 0.36401367, 3.5859375, 2.5644531, 3.1894531, ...])), passed: false } for const
DEBUG onnx_ir::from_onnx: adding node "conv2d6"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Sigmoid"
DEBUG onnx_ir::from_onnx: renaming node "/model.2/cv2/act/Sigmoid"
DEBUG onnx_ir::from_onnx: adding node "sigmoid6"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Mul"
DEBUG onnx_ir::from_onnx: renaming node "/model.2/cv2/act/Mul"
DEBUG onnx_ir::from_onnx: adding node "mul6"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Conv"
DEBUG onnx_ir::from_onnx: renaming node "/model.3/conv/Conv"
DEBUG onnx_ir::from_onnx: checking node conv2d7 for constants
DEBUG onnx_ir::from_onnx: checking input Argument { name: "model.3.conv.weight", ty: Tensor(TensorType { elem_type: Float32, dim: 4, shape: Some([64, 32, 3, 3]) }), value: Some(Float32s([0.008285522, 0.00031018257, -0.009002686, -0.023864746, -0.06591797, -0.04006958, -0.013717651, ...])), passed: false } for const
DEBUG onnx_ir::from_onnx: checking input Argument { name: "model.3.conv.bias", ty: Tensor(TensorType { elem_type: Float32, dim: 1, shape: Some([64]) }), value: Some(Float32s([0.7006836, 0.6904297, 3.4414063, 1.2470703, -0.92529297, 1.2861328, -0.15722656, ...])), passed: false } for const
DEBUG onnx_ir::from_onnx: adding node "conv2d7"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Sigmoid"
DEBUG onnx_ir::from_onnx: renaming node "/model.3/act/Sigmoid"
DEBUG onnx_ir::from_onnx: adding node "sigmoid7"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Mul"
DEBUG onnx_ir::from_onnx: renaming node "/model.3/act/Mul"
DEBUG onnx_ir::from_onnx: adding node "mul7"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Conv"
DEBUG onnx_ir::from_onnx: renaming node "/model.4/cv1/conv/Conv"
DEBUG onnx_ir::from_onnx: checking node conv2d8 for constants
DEBUG onnx_ir::from_onnx: checking input Argument { name: "model.4.cv1.conv.weight", ty: Tensor(TensorType { elem_type: Float32, dim: 4, shape: Some([64, 64, 1, 1]) }), value: Some(Float32s([-0.12878418, 0.31835938, 0.04083252, 0.01209259, -0.546875, -0.15966797, -0.20336914, ...])), passed: false } for const
DEBUG onnx_ir::from_onnx: checking input Argument { name: "model.4.cv1.conv.bias", ty: Tensor(TensorType { elem_type: Float32, dim: 1, shape: Some([64]) }), value: Some(Float32s([0.64941406, 1.1298828, 3.0371094, -0.3557129, 2.453125, -3.0019531, 0.03189087, ...])), passed: false } for const
DEBUG onnx_ir::from_onnx: adding node "conv2d8"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Sigmoid"
DEBUG onnx_ir::from_onnx: renaming node "/model.4/cv1/act/Sigmoid"
DEBUG onnx_ir::from_onnx: adding node "sigmoid8"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Mul"
DEBUG onnx_ir::from_onnx: renaming node "/model.4/cv1/act/Mul"
DEBUG onnx_ir::from_onnx: adding node "mul8"
DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Split"
DEBUG onnx_ir::from_onnx: renaming node "/model.4/Split"
ERROR burn_import::logger: PANIC => panicked at crates/onnx-ir/src/dim_inference.rs:914:17:
Split: Input tensor shape is not defined
thread 'main' panicked at crates/onnx-ir/src/dim_inference.rs:914:17:
Split: Input tensor shape is not defined
``` 
</details>

Thank you for telling me to run the test!

**Comment by laggui** [comment]
In this case, feel free to reopen the issue or open a new one with the new scope.

**Comment by Luni-4** [comment]
Done both of your suggestions

**Comment by polarathene** [comment]
## Reproduction

For reference, using the current git version of Burn (_has some improvements since the latest release tag [`v0.17.1`](https://github.com/tracel-ai/burn/releases/tag/v0.17.1)_).

Reproduction uses [this `compose.yaml`](https://github.com/tracel-ai/burn/issues/1714#issuecomment-2952373124).

```bash
curl -fsSL -o yolo.zip https://github.com/burn-rs/burn/files/12411142/yolov8n.zip
unzip yolo.zip

docker compose run --rm -it --name onnx-example -v ./yolov8n.onnx:/example/src/model/example.onnx burn-onnx-import bash
printf '%s\n' 'src/model/example.onnx' 'src/model/example.onnx' | ./onnx-opset-upgrade.py
cargo build
```

```rust
   INFO onnx_ir::from_onnx: Parsing ONNX file: src/model/example.onnx
  ERROR burn_import::logger: PANIC => panicked at /root/.cargo/git/checkouts/burn-6c277d792b0d5d7a/1f5ccd4/crates/onnx-ir/src/from_onnx.rs:381:5:
  Nodes are not topologically sorted
```

**Comment by antimora** [comment]
"Nodes are not topologically sorted" error was fixed in #3284
 
Now, there is another issue remains that I have described here: https://github.com/tracel-ai/burn/issues/600#issuecomment-3059448861 

If you need to use this model, you can upgrade/simplify it using [onnx-simplifier](https://github.com/daquexian/onnx-simplifier).

**Comment by Luni-4** [comment]
Thank you @antimora!

**Comment by antimora** [comment]
I am working on fixing an issue for loading yolo11x described here related to Slice OP: https://github.com/tracel-ai/burn/issues/2822

**Comment by polarathene** [comment]
> If you need to use this model, you can upgrade/simplify it using [onnx-simplifier](https://github.com/daquexian/onnx-simplifier).

Were you successfully importing the model with the simplifier?

```console
$ curl -fsSL -o yolo.zip https://github.com/burn-rs/burn/files/12411142/yolov8n.zip && \
  unzip yolo.zip && rm yolo.zip && \
  mv yolov8n.onnx src/model/example.onnx

$ printf '%s\n' 'src/model/example.onnx' 'src/model/example.onnx' | ./onnx-opset-upgrade.py

$ uv tool install onnxsim-prebuilt --with onnxruntime
$ onnxsim src/model/example.onnx src/model/example.onnx

$ cargo build
  DEBUG burn_import::burn::graph: Registering node => 'concat'
   INFO burn_core::record::file: File exists, replacing
  DEBUG burn_import::burn::graph: Building the scope nodes len => '234'
  ERROR burn_import::logger: PANIC => panicked at /root/.cargo/git/checkouts/burn-6c277d792b0d5d7a/38874eb/crates/burn-import/src/burn/scope.rs:43:13:
  No variable with name _model_22_Constant_9_output_0
```
